#------------------------------------------------------------------------------#
#
# @file     latexmkrc
# @author	Eric Poirier
# @date		December 2017
# @version	1.0
#
# This file provides option for the automated building process of the LaTeX file
# connectXGuiSpec.tex. For more information, check this link:
#
#                      http://mg.readthedocs.io/latexmk.html
#
#------------------------------------------------------------------------------#

$pdf_mode = "1";
