#------------------------------------------------------------------------------#
#
# @file     latexmkrc
# @author	Eric Poirier
# @date		March 2017
# @version	1
#
# This file provides option for the automated building process of the LaTeX file
# cx_cpp_norm.tex. For more information, check this link: 
# 
#                      http://mg.readthedocs.io/latexmk.html
#
#------------------------------------------------------------------------------#

$pdf_mode = "1";
